### ISSUE TITLE
Game crashes when an Item is attacked

### ISSUE THREAD

**Issue by gusanoloco** [joshuaskelly/lunch-break-rl#1]
If you happen to attack a tile with an item in it the game crashes.

happened to me when using the whip and a dagger was in a tile past an enemy.
Error AttributeError: 'Dagger' object has no attribute 'alive'

attackaction.py line 32

![image](https://user-images.githubusercontent.com/595570/29694691-bfcced10-8903-11e7-8327-4a743d80260d.png)

**Comment by joshuaskelly** [comment]
## Summary
This was introduced in 78e05809b949a281a4cf9dc0840dc5d6732801ef and fixed in 50456b4ba9f65a14da436226c427745341ef638e.

## Details
I incorrectly introduced a check for ```target.alive``` because I was seeing actions being performed on dead creatures. The real issue was I overloaded ```RatClaws.get_special_action()``` that did side-effecty stuff but did not return an action. Returning the side effect stuff wrapped in an ```Action``` was the correct thing to do here.
